# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import imageservice_pb2 as imageservice__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in imageservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImage = channel.unary_unary(
                '/imageservice.ImageService/UploadImage',
                request_serializer=imageservice__pb2.ImageUploadRequest.SerializeToString,
                response_deserializer=imageservice__pb2.ImageUploadResponse.FromString,
                _registered_method=True)
        self.DownloadImage = channel.unary_unary(
                '/imageservice.ImageService/DownloadImage',
                request_serializer=imageservice__pb2.ImageDownloadRequest.SerializeToString,
                response_deserializer=imageservice__pb2.ImageDownloadResponse.FromString,
                _registered_method=True)
        self.PredictImage = channel.unary_unary(
                '/imageservice.ImageService/PredictImage',
                request_serializer=imageservice__pb2.ImageDownloadRequest.SerializeToString,
                response_deserializer=imageservice__pb2.ImagePredictionResponse.FromString,
                _registered_method=True)


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=imageservice__pb2.ImageUploadRequest.FromString,
                    response_serializer=imageservice__pb2.ImageUploadResponse.SerializeToString,
            ),
            'DownloadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadImage,
                    request_deserializer=imageservice__pb2.ImageDownloadRequest.FromString,
                    response_serializer=imageservice__pb2.ImageDownloadResponse.SerializeToString,
            ),
            'PredictImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictImage,
                    request_deserializer=imageservice__pb2.ImageDownloadRequest.FromString,
                    response_serializer=imageservice__pb2.ImagePredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageservice.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageservice.ImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageservice.ImageService/UploadImage',
            imageservice__pb2.ImageUploadRequest.SerializeToString,
            imageservice__pb2.ImageUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageservice.ImageService/DownloadImage',
            imageservice__pb2.ImageDownloadRequest.SerializeToString,
            imageservice__pb2.ImageDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageservice.ImageService/PredictImage',
            imageservice__pb2.ImageDownloadRequest.SerializeToString,
            imageservice__pb2.ImagePredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
